### ISSUE TITLE
500 crash when querying OPTIONS to view schema in API

### ISSUE THREAD

**Issue by jathanism** [dropbox/nsot#126]
Log:
```python
[2015-11-19 12:46:52 +0000] [31513] [ERROR] Internal Server Error: /api/sites/1/networks/
Traceback (most recent call last):
  File "/home/jathan/sandbox/virtualenvs/nsot/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jathan/sandbox/virtualenvs/nsot/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/jathan/sandbox/virtualenvs/nsot/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jathan/sandbox/virtualenvs/nsot/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/jathan/sandbox/virtualenvs/nsot/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/jathan/sandbox/virtualenvs/nsot/local/lib/python2.7/site-packages/rest_framework/views.py", line 477, in options
    data = self.metadata_class().determine_metadata(request, self)
  File "/home/jathan/sandbox/virtualenvs/nsot/local/lib/python2.7/site-packages/rest_framework/metadata.py", line 68, in determine_metadata
    actions = self.determine_actions(request, view)
  File "/home/jathan/sandbox/virtualenvs/nsot/local/lib/python2.7/site-packages/rest_framework/metadata.py", line 87, in determine_actions
    view.get_object()
  File "/home/jathan/sandbox/virtualenvs/nsot/local/lib/python2.7/site-packages/rest_framework/generics.py", line 93, in get_object
    (self.__class__.__name__, lookup_url_kwarg)
AssertionError: Expected view NetworkViewSet to be called with a URL keyword argument named "pk". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly.
[2015-11-19 12:46:52 +0000] [31513] [INFO] 500 POST /api/sites/1/networks/ (127.0.0.1) 39.23ms
```

This happens in both browsable and JSON API.

**Comment by jathanism** [comment]
Looks like it's related to the bulk update (PUT) functionality. If I comment that out, it works as expected.

We're using `django-rest-framework-bulk` for this.
