### ISSUE TITLE
API throws exception when attempting to add duplicate network

### ISSUE THREAD

**Issue by dmar42** [dropbox/nsot#142]
The API server seems to be unhappy if you try to create a network that already exists. 

Adding a new network works fine
```
$ DEBUG=1 nsot --verbose networks add --cidr 192.168.0.0/16
DEBUG:pynsot.commands.callbacks:TRANSFORM_ATTRIBUTES [IN]: ()
DEBUG:pynsot.commands.callbacks:TRANSFORM_ATTRIBUTES [OUT]: {}
DEBUG:pynsot.client:Reading dotfile.
DEBUG:pynsot.client:Validating auth_method: auth_header
DEBUG:pynsot.commands.callbacks:GOT DEFAULT_SITE: 1
DEBUG:pynsot.commands.callbacks:GOT PROVIDED SITE_ID: None
<type 'dict'>
DEBUG:pynsot.app:adding {'bulk_add': None, 'attributes': {}, 'cidr': u'192.168.0.0/16', 'site_id': '1'}
DEBUG:pynsot.app:rebase: Got site_id: 1
DEBUG:pynsot.app:rebase: Site_id found; rebasing API URL!
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:requests.packages.urllib3.connectionpool:"POST /api/sites/1/networks/ HTTP/1.1" 201 None
DEBUG:pynsot.app:PRETTY DICT INCOMING DATA = {'bulk_add': None, 'attributes': {}, 'cidr': u'192.168.0.0/16'}
[SUCCESS] Added network!
```

Attempting to add the same network again from the pynsot client, throws an exception
```
$ DEBUG=1 nsot --verbose networks add --cidr 192.168.0.0/16
DEBUG:pynsot.commands.callbacks:TRANSFORM_ATTRIBUTES [IN]: ()
DEBUG:pynsot.commands.callbacks:TRANSFORM_ATTRIBUTES [OUT]: {}
DEBUG:pynsot.client:Reading dotfile.
DEBUG:pynsot.client:Validating auth_method: auth_header
DEBUG:pynsot.commands.callbacks:GOT DEFAULT_SITE: 1
DEBUG:pynsot.commands.callbacks:GOT PROVIDED SITE_ID: None
<type 'dict'>
DEBUG:pynsot.app:adding {'bulk_add': None, 'attributes': {}, 'cidr': u'192.168.0.0/16', 'site_id': '1'}
DEBUG:pynsot.app:rebase: Got site_id: 1
DEBUG:pynsot.app:rebase: Site_id found; rebasing API URL!
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:requests.packages.urllib3.connectionpool:"POST /api/sites/1/networks/ HTTP/1.1" 500 None
Traceback (most recent call last):
  File "/Users/dmar/venv/nsot/bin/nsot", line 9, in <module>
    load_entry_point('pynsot==0.18', 'console_scripts', 'nsot')()
  File "/Users/dmar/venv/nsot/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dmar/venv/nsot/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/dmar/venv/nsot/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dmar/venv/nsot/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dmar/venv/nsot/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dmar/venv/nsot/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/dmar/venv/nsot/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/dmar/github/pynsot/pynsot/commands/cmd_networks.py", line 118, in add
    ctx.obj.add(data)
  File "/Users/dmar/github/pynsot/pynsot/app.py", line 418, in add
    self.handle_error(action, data, err)
  File "/Users/dmar/github/pynsot/pynsot/app.py", line 203, in handle_error
    body = resp.json()
  File "/Users/dmar/venv/nsot/lib/python2.7/site-packages/requests/models.py", line 799, in json
    return json.loads(self.text, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

This message appears to be coming from the nsot server
```
[2016-02-12 13:39:02 -0600] [3039] [ERROR] Internal Server Error: /api/sites/1/networks/
Traceback (most recent call last):
  File "/Users/dmar/venv/nsot/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/Users/dmar/venv/nsot/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/Users/dmar/venv/nsot/lib/python2.7/site-packages/rest_framework/response.py", line 71, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "/Users/dmar/venv/nsot/lib/python2.7/site-packages/rest_framework/renderers.py", line 104, in render
    separators=separators
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/Users/dmar/venv/nsot/lib/python2.7/site-packages/rest_framework/utils/encoders.py", line 64, in default
    return super(JSONEncoder, self).default(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: ValidationError([u'Network with this Site, Ip version, Network address and Prefix length already exists.']) is not JSON serializable
[2016-02-12 13:39:02 -0600] [3039] [INFO] 500 POST /api/sites/1/networks/ (127.0.0.1) 26.81ms
```

**Comment by coxley** [comment]
I'm coming across this too. Normally I had been doing this to handle this:

```python
try:
    client.attributes.post(resources)
except Exception as e:
    if not e.content['message'] and e.content['code'] == 400:
        logit('Duplicate resource, continuing...')
