### ISSUE TITLE
Updating Interface: HTTP 500

### ISSUE THREAD

**Issue by coxley** [dropbox/nsot#168]
Spent a good amount of time drilling into cause of these 500s. I've now narrowed it down to this PATCH works when `d['addresses']` is set to empty list or addresses that don't have resources associated with them. However it does fail if it contains existing networks.

Here's proof:

```python
In [95]: d
Out[95]: 
{'addresses': ['10.97.3.113/32', 'fe80::82e6:50ff:fe0d:fc2e/128'],
 'attributes': {},
 'description': 'wlp2s0 on yelp-coxley',
 'device': 1,
 'id': 1,
 'mac_address': '80:e6:50:0d:fc:2e',
 'name': 'wlp2s0',
 'site_id': 2,
 'type': 6}

In [96]: c.sites(2).interfaces.patch([d])
HttpServerError: Server Error 500: http://localhost:8990/api/sites/2/interfaces/

In [97]: d['addresses'] = []
In [98]: c.sites(2).interfaces.patch([d])
Out[98]: 
[{u'addresses': [],
  u'attributes': {},
  u'description': u'wlp2s0 on yelp-coxley',
  u'device': 1,
  u'id': 1,
  u'mac_address': u'80:E6:50:0D:FC:2E',
  u'name': u'wlp2s0',
  u'networks': [],
  u'parent_id': None,
  u'speed': 1000,
  u'type': 6}]

In [99]: d['addresses'] = ['10.97.3.145/32']
In [100]: c.sites(2).interfaces.patch([d])
Out[100]: 
[{u'addresses': [u'10.97.3.145/32'],
  u'attributes': {},
  u'description': u'wlp2s0 on yelp-coxley',
  u'device': 1,
  u'id': 1,
  u'mac_address': u'80:E6:50:0D:FC:2E',
  u'name': u'wlp2s0',
  u'networks': [u'0.0.0.0/0'],
  u'parent_id': None,
  u'speed': 1000,
  u'type': 6}]

In [101]: d['addresses'] = ['fe80::82e6:50ff:fe0d:fc2e/128']
In [102]: c.sites(2).interfaces.patch([d])
HttpServerError: Server Error 500: http://localhost:8990/api/sites/2/interfaces/

```

**Comment by coxley** [comment]
Ran into this again and forgot about this ticket!

**Comment by jathanism** [comment]
I have been unable to reproduce this. Can you please try this against nsot 0.15.9? And see if you can reproduce it and if so, can you please add some more context?

**Comment by coxley** [comment]
Reproduced on my side.

```python

In [28]: c.sites(1).networks.get()[-1]
Out[28]: 
{u'attributes': {u'desc': u'vethe424b9a on yelp-coxley'},
 u'id': 55,
 u'ip_version': u'6',
 u'is_ip': True,
 u'network_address': u'fe80::d4f9:c3ff:fedd:1ecd',
 u'parent_id': 2,
 u'prefix_length': 128,
 u'site_id': 1,
 u'state': u'assigned'}
​
In [29]: c.sites(1).interfaces.get()[0]
Out[29]: 
{u'addresses': [],
 u'attributes': {},
 u'description': u'wlp2s0 on yelp-coxley',
 u'device': 5,
 u'id': 13,
 u'mac_address': u'80:E6:50:0D:FC:2E',
 u'name': u'wlp2s0',
 u'networks': [],
 u'parent_id': None,
 u'speed': 1000,
 u'type': 6}
​
In [30]: intf = c.sites(1).interfaces.get()[0]
​
In [31]: intf['addresses'] = ['fe80::d4f9:c3ff:fedd:1ecd']
​
In [32]: c.sites(1).interfaces.patch([intf])
---------------------------------------------------------------------------
HttpServerError                           Traceback (most recent call last)
<ipython-input-32-6828ac2d0e55> in <module>()
----> 1 c.sites(1).interfaces.patch([intf])
​
/home/codey/docs/envs/pynsot/lib/python2.7/site-packages/slumber/__init__.pyc in patch(self, data, files, **kwargs)
    169 
    170     def patch(self, data=None, files=None, **kwargs):
--> 171         resp = self._request("PATCH", data=data, files=files, params=kwargs)
    172         return self._process_response(resp)
    173 
​
/home/codey/docs/envs/pynsot/lib/python2.7/site-packages/slumber/__init__.pyc in _request(self, method, data, files, params)
    101             raise exception_class("Client Error %s: %s" % (resp.status_code, url), response=resp, content=resp.content)
    102         elif 500 <= resp.status_code <= 599:
--> 103             raise exceptions.HttpServerError("Server Error %s: %s" % (resp.status_code, url), response=resp, content=resp.content)
    104 
    105         self._ = resp
​
HttpServerError: Server Error 500: http://localhost:8990/api/sites/1/interfaces/
```


Django logs

```python
[2016-03-28 17:43:21 +0000] [23] [ERROR] Internal Server Error: /api/sites/1/interfaces/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework_bulk/drf3/mixins.py", line 79, in partial_bulk_update
    return self.bulk_update(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework_bulk/drf3/mixins.py", line 74, in bulk_update
    self.perform_bulk_update(serializer)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework_bulk/drf3/mixins.py", line 85, in perform_bulk_update
    return self.perform_update(serializer)
  File "/usr/local/lib/python2.7/dist-packages/nsot/api/views.py", line 356, in perform_update
    serializer
  File "/usr/local/lib/python2.7/dist-packages/nsot/api/views.py", line 290, in perform_update
    objects = serializer.save()
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 654, in save
    self.instance = self.update(self.instance, validated_data)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework_bulk/drf3/serializers.py", line 68, in update
    updated_objects.append(self.child.update(obj, obj_validated_data))
  File "/usr/local/lib/python2.7/dist-packages/nsot/api/serializers.py", line 460, in update
    obj.set_addresses(addresses, overwrite=True, partial=self.partial)
  File "/usr/local/lib/python2.7/dist-packages/nsot/models.py", line 1242, in set_addresses
    self.assign_address(insert)
  File "/usr/local/lib/python2.7/dist-packages/nsot/models.py", line 1180, in assign_address
    address = Network.objects.get_by_address(cidr)
  File "/usr/local/lib/python2.7/dist-packages/nsot/models.py", line 555, in get_by_address
    address = Network.objects.get(**lookup_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 338, in get
    (self.model._meta.object_name, num)
MultipleObjectsReturned: get() returned more than one Network -- it returned 2!
[2016-03-28 17:43:21 +0000] [23] [INFO] 500 PATCH /api/sites/1/interfaces/ (172.17.0.1) 71.53ms
```

**Comment by jathanism** [comment]
Ok, so it's an error related to multiple networks being returned when looking one up to associate it to an interface. It's related to site_id not being taken into consideration on the lookup, which it should be.

And it would only pop up if you had 2 sites w/ a matching Network object.

Good catch! And we'll get this fixed w/ a regression test. :)
