### ISSUE TITLE
Error cryptography dependency and Ubuntu 16.04

### ISSUE THREAD

**Issue by slinderud** [dropbox/nsot#213]
Getting this exact error:
https://github.com/cuckoosandbox/cuckoo/issues/889

Apparently, updating the dependency to a newer version should fix this.

**Comment by jathanism** [comment]
Hmm... Thanks for the report. Ubuntu 16.04 is untested so far. If you could try the same fix to `requirements.txt` and provide a patch that would be excellent!!

**Comment by slinderud** [comment]
changed requirements to cryptography==1.4.
Would then complain that ciffi was >=1.4.1. So changed that one aswell.

nsot-server init worked fine. When i tried to start it i got this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/nsot-server", line 9, in <module>
    load_entry_point('nsot==1.0.1', 'console_scripts', 'nsot-server')()
  File "/usr/local/lib/python2.7/dist-packages/nsot/util/core.py", line 276, in main
    initializer=initialize_app,
  File "/usr/local/lib/python2.7/dist-packages/logan/runner.py", line 193, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/nsot/util/commands.py", line 56, in execute
    super(NsotCommand, self).execute(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/nsot/management/commands/start.py", line 134, in handle
    call_command('collectstatic', interactive=False, ignore=['src'])
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 168, in handle
    collected = self.collect()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 98, in collect
    for path, storage in finder.list(self.ignore_patterns):
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/finders.py", line 112, in list
    for path in utils.get_files(storage, ignore_patterns):
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/utils.py", line 28, in get_files
    directories, files = storage.listdir(location)
  File "/usr/local/lib/python2.7/dist-packages/django/core/files/storage.py", line 299, in listdir
    for entry in os.listdir(path):
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/nsot/static'
```

**Comment by jathanism** [comment]
Hm ok, that's because your development environment isn't setup. See here:

http://nsot.readthedocs.io/en/latest/development.html

That error is due to the fact that we are using Bower to pull in JavaScript dependencies for the web UI prior to publishing the package to PyPI.

If you have NPM available, the setup steps are (`setup.py build_static` is what requires `npm`):

```
$ python setup.py develop
$ python setup.py build_static
```

Then you may `setup.py install` and test `nsot-server` again. 

If you'd like to go ahead and try this out, please do. Meanwhile I'm getting an Ubuntu 16.04 VM up and running to go ahead and test this myself. Thanks!

**Comment by jathanism** [comment]
Ok I got it working on Ubuntu 16.04. I'll go ahead and publish a fix.
