### ISSUE TITLE
Crash w/ djangorestframework==3.5.0

### ISSUE THREAD

**Issue by jathanism** [dropbox/nsot#227]
**TL;DR:** DRF 3.5.0 requires `django-filter>=0.15.3` and new installs are gonna crash if we don't address this.

The requirements currently have `djangorestframework>=3.4.4` and `django-filter==0.13.0`

On a fresh install w/ the release of DRF 3.5.0 this is happening:

```
[20/Oct/2016 11:28:09] "GET /api/sites/?limit=1 HTTP/1.1" 500 1321
[2016-10-20 11:28:09 +0000] [50273] [ERROR] Internal Server Error: /api/sites/
Traceback (most recent call last):
  File "/home/jathan/sandbox/virtualenvs/nsot/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jathan/sandbox/virtualenvs/nsot/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/jathan/sandbox/virtualenvs/nsot/lib/python2.7/site-packages/rest_framework/viewsets.py", line 83, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jathan/sandbox/virtualenvs/nsot/lib/python2.7/site-packages/rest_framework/views.py", line 477, in dispatch
    response = self.handle_exception(exc)
  File "/home/jathan/sandbox/virtualenvs/nsot/lib/python2.7/site-packages/rest_framework/views.py", line 437, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/jathan/sandbox/virtualenvs/nsot/lib/python2.7/site-packages/rest_framework/views.py", line 474, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/jathan/sandbox/virtualenvs/nsot/lib/python2.7/site-packages/nsot/api/views.py", line 64, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/jathan/sandbox/virtualenvs/nsot/lib/python2.7/site-packages/rest_framework/generics.py", line 151, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "/home/jathan/sandbox/virtualenvs/nsot/lib/python2.7/site-packages/rest_framework/filters.py", line 57, in __new__
    assert django_filters.VERSION >= (0, 15, 3), 'django-filter 0.15.3 and above is required'
AssertionError: django-filter 0.15.3 and above is required
[2016-10-20 11:28:09 +0000] [50273] [INFO] 500 GET /api/sites/ (127.0.0.1) 14.67ms
[20/Oct/2016 11:28:09] "GET /api/sites/ HTTP/1.1" 500 1321
```

**Comment by jathanism** [comment]
Fixed in #229
