### ISSUE TITLE
ValueError when performing database upgrade to v1.0.9

### ISSUE THREAD

**Issue by jathanism** [dropbox/nsot#236]
When upgrading to v1.0.9 this happens:

```
$ nsot-server upgrade
Operations to perform:
  Synchronize unmigrated apps: django_filters, staticfiles, messages, smart_selects, rest_framework_swagger, django_extensions, rest_framework, custom_user
  Apply all migrations: admin, contenttypes, nsot, auth, sessions
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying nsot.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying nsot.0002_auto_20150810_1718... OK
  Applying nsot.0003_auto_20150810_1751... OK
  Applying nsot.0004_auto_20150810_1806... OK
  Applying nsot.0005_auto_20150810_1847... OK
  Applying nsot.0006_auto_20150810_1947... OK
  Applying nsot.0007_auto_20150811_1201... OK
  Applying nsot.0008_auto_20150811_1222... OK
  Applying nsot.0009_auto_20150811_1245... OK
  Applying nsot.0010_auto_20150921_2120... OK
  Applying nsot.0011_auto_20150930_1557... OK
  Applying nsot.0012_auto_20151002_1427... OK
  Applying nsot.0013_auto_20151002_1443... OK
  Applying nsot.0014_auto_20151002_1653... OK
  Applying nsot.0015_move_attribute_fields... OK
  Applying nsot.0016_move_device_data... OK
  Applying nsot.0017_move_network_data... OK
  Applying nsot.0018_move_interface_data... OK
  Applying nsot.0019_move_assignment_data... OK
  Applying nsot.0020_move_value_data... OK
  Applying nsot.0021_remove_resource_object... OK
  Applying nsot.0022_auto_20151007_1847... OK
  Applying nsot.0023_auto_20151008_1351... OK
  Applying nsot.0024_network_state... OK
  Applying nsot.0025_value_site... OK
  Applying nsot.0026_model_field_verbose_names...Traceback (most recent call last):
  File "/home/dmar/venv/nsot/bin/nsot-server", line 11, in <module>
    load_entry_point('nsot', 'console_scripts', 'nsot-server')()
  File "/home/dmar/github/nsot/nsot/util/core.py", line 276, in main
    initializer=initialize_app,
  File "/home/dmar/venv/nsot/local/lib/python2.7/site-packages/logan/runner.py", line 193, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/home/dmar/venv/nsot/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/dmar/venv/nsot/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/dmar/venv/nsot/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/dmar/github/nsot/nsot/util/commands.py", line 56, in execute
    super(NsotCommand, self).execute(*args, **options)
  File "/home/dmar/venv/nsot/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/dmar/github/nsot/nsot/management/commands/upgrade.py", line 29, in handle
    verbosity=options['verbosity'],
  File "/home/dmar/venv/nsot/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/home/dmar/venv/nsot/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/dmar/venv/nsot/local/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 25, in handle
    call_command("migrate", **options)
  File "/home/dmar/venv/nsot/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/home/dmar/venv/nsot/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/dmar/venv/nsot/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/dmar/venv/nsot/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/home/dmar/venv/nsot/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/dmar/venv/nsot/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/dmar/venv/nsot/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 201, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/home/dmar/venv/nsot/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 484, in alter_field
    old_db_params, new_db_params, strict)
  File "/home/dmar/venv/nsot/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 566, in _alter_field
    old_default = self.effective_default(old_field)
  File "/home/dmar/venv/nsot/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 211, in effective_default
    default = field.get_db_prep_save(default, self.connection)
  File "/home/dmar/venv/nsot/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 710, in get_db_prep_save
    prepared=False)
  File "/home/dmar/github/nsot/nsot/fields.py", line 89, in get_db_prep_value
    return ipaddress.ip_address(value).packed
  File "/home/dmar/venv/nsot/local/lib/python2.7/site-packages/ipaddress.py", line 166, in ip_address
    address)
ValueError: None does not appear to be an IPv4 or IPv6 address
```

It appears this may only occur w/ a MySQL backend. Need to confirm and really get to the bottom of it.

**Comment by jathanism** [comment]
Fixed in #237
